"""Print every garment currently in the DB -- sku, status, name, and id --
so you've got something to paste into the Passport Scanner's manual-id
input or open as a barcode, without hand-writing a sqlite query each time.

Garment ids are random UUIDs regenerated by every seed.py run, so this list
goes stale the moment someone reseeds; re-run this whenever you need a
current one.

Run with the venv's python:
    backend/venv/Scripts/python.exe backend/list_garments.py [status]

Optional `status` argument filters to one status (active | resale | returned).
"""

import sys

import models
from database import SessionLocal

# Matches the proxy paths vite.config.js forwards to the backend, so this is
# the same URL the frontend dev server would resolve /static/barcode/... to.
BARCODE_URL_BASE = "http://127.0.0.1:8000/static/barcode"


def main():
    status_filter = sys.argv[1] if len(sys.argv) > 1 else None

    db = SessionLocal()
    try:
        query = db.query(models.Garment).order_by(models.Garment.sku)
        if status_filter:
            query = query.filter(models.Garment.current_status == status_filter)
        garments = query.all()

        if not garments:
            print(f"No garments found (status={status_filter!r}).")
            return

        for g in garments:
            print(f"{g.sku}  {g.current_status:<8}  {g.product_name}")
            print(f"    id:  {g.id}")
            print(f"    barcode:  {BARCODE_URL_BASE}/{g.id}.png")
        print(f"\n{len(garments)} garment(s).")
    finally:
        db.close()


if __name__ == "__main__":
    main()
